spring.application.name=React
spring.datasource.url=jdbc:mysql://localhost:3306/prison_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia%2FKolkata
spring.datasource.username=root
spring.datasource.password=7004201625

spring.jpa.hibernate.ddl-auto=update

server.port=8081

# HikariCP specific settings to improve resilience
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.validation-timeout=3000
